[package]
name = "multicoin"
version = "0.0.1"
published-at = ""
edition = "2024"

[dependencies]

[addresses]
# Will be rewritten on publish
admin =  "0x0"
multicoin =  "0x0"


# [dev-addresses]
# admin =  "0xA11CE"

[build]
# (Removed unsupported 'docs' field causing warnings)

#[lint]
# Lint configuration placeholder (commented out due to schema warnings)
